import EvmCompiler.Yul.NoCallRuntime

/-!
Current public theorem spine.

This module intentionally exposes only the preferred public imported-Yul to
gas-aware EVM theorem roots. Solidity and object/Yul-object interfaces live in
their own modules; this audit file should not keep stale theorem routes alive.
-/

namespace EvmCompiler
namespace LayerAudit
namespace ImportedYulBoundary

abbrev recursiveBridgeTopToGasAwareEVM :=
  @Yul.Program.compile_whole_program_result_sound_of_recursiveBridgeAllBoundsReserved_topNoCall_sourceCompile_structuredPrimitive_canonicalEntry_sourceStaticFeatureResourceBytecodeChecked_canonicalObservation_codeImage_existsSourceRun_exprResultContracts_sufficientGas_stepTrace_instrCoreResources_finalization_noReturnDataCopy_X

abbrev recursiveBridgeTopToGasAwareEVMNoOutOfGas :=
  @Yul.Program.compile_whole_program_result_no_out_of_gas_of_recursiveBridgeAllBoundsReserved_topNoCall_sourceCompile_structuredPrimitive_canonicalEntry_sourceStaticFeatureResourceBytecodeChecked_canonicalObservation_codeImage_existsSourceRun_exprResultContracts_sufficientGas_instrCoreResources_finalization_noReturnDataCopy_X

end ImportedYulBoundary
end LayerAudit
end EvmCompiler
