import EvmCompiler.Yul.OpenGasAware
import EvmCompiler.Yul.OpenRuntime

#print axioms EvmCompiler.Yul.OpenGasAware.OpenXCommittedSafeAt.to_outcome_safety
#print axioms EvmCompiler.Yul.Program.RecursiveBridgeCALLFamilyRegularOpenAssemblyInferredBoundStackSafeNoReturnDataCopyTopAssumptions.openXContractLivenessAndSafetyOutcomeSafetyAtGas
#print axioms EvmCompiler.Yul.Program.RecursiveBridgeCALLFamilyRegularOpenAssemblyInferredBoundStackSafeNoReturnDataCopyTopAssumptions.openXContractLivenessAndSafetyResultOrFailureAtGas
