import EvmCompiler.Yul.OpenGasAware
import EvmCompiler.Yul.OpenRuntime
import EvmCompiler.LayerAudit

#print axioms EvmCompiler.Yul.Program.compileCheckedAssemblyTargetBytecodeResourcesCALLFamilyFeaturesSourceStaticRegularOpenAssemblyInferredBoundStackSafe?_currentNoCallReturnDataCopyBoundsReady
#print axioms EvmCompiler.LayerAudit.ImportedYulOpenCALLBoundary.checkedImportedYulCallCreateOutcomeSafetyAtGas
#print axioms EvmCompiler.LayerAudit.ImportedYulOpenCALLBoundary.checkedImportedYulCallCreateResultOrFailureAtGas
