import EvmCompiler.Yul.OpenGasAware
import EvmCompiler.Yul.OpenRuntime

#print axioms EvmCompiler.Yul.OpenGasAware.OpenXCommittedSafeAt.to_outcome_safety
#print axioms EvmCompiler.Yul.Program.compileCheckedCALLFamilyRegularOpenAssemblyInferredBoundStackSafeNoReturnDataCopy_sourceOpenDispatcherBlockResult_openXContractLivenessAndSafetyOutcomeSafetyAtGas_of_checked_traceAccepted_sourceBridgeNoArtificialCapExternalWorldReady_noReturnDataCopy
#print axioms EvmCompiler.Yul.Program.compileCheckedCALLFamilyRegularOpenAssemblyInferredBoundStackSafeNoReturnDataCopy_sourceOpenDispatcherBlockResult_openXContractLivenessAndSafetyResultOrFailureAtGas_of_checked_traceAccepted_sourceBridgeNoArtificialCapExternalWorldReady_noReturnDataCopy
